import Head from 'next/head'

import { useGetNfts } from '@/hooks/useGetNfts'
import { Search } from '@/components/Search/Search'
import { NFTGallery } from '@/components/NFTGallery/NFTGallery'
import Header from '@/components/Header/Header';


export default function Home() {
    const [
        isLoading,
        data,
        onGetByAddress,
    ] = useGetNfts();

    return (
        <>
            <Head>
                <title>Encode Bootcamp Final Project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Search onSearch={onGetByAddress} />
                <NFTGallery
                    isLoading={isLoading}
                    data={data}
                />
            </main>
        </>
    )
}
