import Head from 'next/head'
import { createGlobalStyle } from 'styled-components';
import { useGetNfts } from '@/hooks/useGetNfts'
import { Search } from '@/components/Search/Search'
import { NFTGallery } from '@/components/NFTGallery/NFTGallery'
import { Web3Provider } from '../../providers/Web3';
import { Navbar } from '@/components/Navbar';

const GlobalStyle = createGlobalStyle`
  body {
    background-color: #111;
    color: #d1bebe;
  }
`;

export default function Home() {
    const [
        isLoading,
        data,
        onGetByAddress,
    ] = useGetNfts();

    return (
        <>
            <Head>
                <title>Encode Bootcamp Final Project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                  <GlobalStyle />

            <main>
            <Web3Provider>
            <Navbar />
                <Search onSearch={onGetByAddress} />
                <NFTGallery
                    isLoading={isLoading}
                    data={data}
                />
                </Web3Provider>
            </main>
        </>
    )
}
